<script lang="ts">
	import { Icon, CodeBlock } from '$lib/ui'
	import pyCode from '$lib/code/textfix.py?raw'
	import tsCode from '$lib/code/everydate.ts?raw'
</script>

<template lang="pug">
	.section
		h2 Programming experience
		.section-content(style="flex-direction: column !important")
			Icon(alt="Python", src="/icons/python.svg", tip="Python", tipindex=100)
			CodeBlock(code="{pyCode}" lang="python" footer="textfix.py - Basic text fixing script.")
		.section-content(style="flex-direction: column !important")
			.icons
				Icon(alt="TypeScript", src="/icons/typescript.svg", tip="TypeScript", tipindex=101)
			CodeBlock(code="{tsCode}" lang="typescript" footer="everydate.ts - Constant generated by calculating the days elapsed since my first everyday.")
</template>

<style lang="scss">
	@use '../../styles/media' as *;
	.section {
		background-color: rgba(var(--light-d-rgb), 0.1);
		flex-direction: column;
		text-align: center;
		display: flex;
		margin: 1rem 0;
		padding: 1rem;
	}

	.section-content {
		flex-direction: column;
		align-items: center;
		display: flex;
		.icons {
			justify-content: center;
			flex-direction: row;
			display: flex;
		}
	}
	@include media('>desktop') {
		.section-content {
			flex-direction: row;
			align-items: center;
			margin: 0.5rem auto;
			width: 80vw;
		}
	}
</style>
